"""empty message

Revision ID: 209ce4f28b6b
Revises: da8e24229271
Create Date: 2022-03-02 15:38:10.710643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209ce4f28b6b'
down_revision = 'da8e24229271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
